//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AssetsManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AssetsManager), typeof(System.Object));
		L.RegFunction("GetLuaBundle", GetLuaBundle);
		L.RegFunction("GetAsset", GetAsset);
		L.RegFunction("ClearAssetsCache", ClearAssetsCache);
		L.RegFunction("New", _CreateAssetsManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAssetsManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				AssetsManager obj = new AssetsManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: AssetsManager.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLuaBundle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AssetsManager obj = (AssetsManager)ToLua.CheckObject(L, 1, typeof(AssetsManager));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.AssetBundle o = obj.GetLuaBundle(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAsset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AssetsManager obj = (AssetsManager)ToLua.CheckObject(L, 1, typeof(AssetsManager));
			string arg0 = ToLua.CheckString(L, 2);
			System.Type arg1 = (System.Type)ToLua.CheckObject(L, 3, typeof(System.Type));
			object o = obj.GetAsset(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearAssetsCache(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AssetsManager obj = (AssetsManager)ToLua.CheckObject(L, 1, typeof(AssetsManager));
			obj.ClearAssetsCache();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, AssetsManager.Instance);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

