//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class KCPNetworkWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(KCPNetwork), typeof(System.Object));
		L.RegFunction("SetReceiveAction", SetReceiveAction);
		L.RegFunction("Init", Init);
		L.RegFunction("Send", Send);
		L.RegFunction("Update", Update);
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("New", _CreateKCPNetwork);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateKCPNetwork(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				KCPNetwork obj = new KCPNetwork();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: KCPNetwork.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetReceiveAction(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			KCPNetwork obj = (KCPNetwork)ToLua.CheckObject(L, 1, typeof(KCPNetwork));
			System.Action<ByteBuffer> arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (System.Action<ByteBuffer>)ToLua.CheckObject(L, 2, typeof(System.Action<ByteBuffer>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(System.Action<ByteBuffer>), func) as System.Action<ByteBuffer>;
			}

			obj.SetReceiveAction(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			KCPNetwork obj = (KCPNetwork)ToLua.CheckObject(L, 1, typeof(KCPNetwork));
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
			int arg3 = (int)LuaDLL.luaL_checknumber(L, 5);
			obj.Init(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Send(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			KCPNetwork obj = (KCPNetwork)ToLua.CheckObject(L, 1, typeof(KCPNetwork));
			byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
			obj.Send(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			KCPNetwork obj = (KCPNetwork)ToLua.CheckObject(L, 1, typeof(KCPNetwork));
			obj.Update();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			KCPNetwork obj = (KCPNetwork)ToLua.CheckObject(L, 1, typeof(KCPNetwork));
			obj.Dispose();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

