//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UDPServerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UDPServer), typeof(System.Object));
		L.RegFunction("ReceiveMsg", ReceiveMsg);
		L.RegFunction("SendUDPMsg", SendUDPMsg);
		L.RegFunction("CloseReceiveSocket", CloseReceiveSocket);
		L.RegFunction("Init", Init);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReceiveMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UDPServer obj = (UDPServer)ToLua.CheckObject(L, 1, typeof(UDPServer));
			obj.ReceiveMsg();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendUDPMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			UDPServer obj = (UDPServer)ToLua.CheckObject(L, 1, typeof(UDPServer));
			byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
			uint arg1 = (uint)LuaDLL.luaL_checknumber(L, 3);
			uint arg2 = (uint)LuaDLL.luaL_checknumber(L, 4);
			obj.SendUDPMsg(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CloseReceiveSocket(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UDPServer obj = (UDPServer)ToLua.CheckObject(L, 1, typeof(UDPServer));
			obj.CloseReceiveSocket();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UDPServer obj = (UDPServer)ToLua.CheckObject(L, 1, typeof(UDPServer));
			obj.Init();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UDPServer.Instance);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

