-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Battle_pb')


local READYREQ = protobuf.Descriptor();
local READYRES = protobuf.Descriptor();
local READYRES_PLAYERID_FIELD = protobuf.FieldDescriptor();
local READYRES_ALLID_FIELD = protobuf.FieldDescriptor();
local READYRES_MODELID_FIELD = protobuf.FieldDescriptor();
local PLAYERACTION = protobuf.Descriptor();
local PLAYERACTION_PLAYERID_FIELD = protobuf.FieldDescriptor();
local PLAYERACTION_X_FIELD = protobuf.FieldDescriptor();
local PLAYERACTION_Y_FIELD = protobuf.FieldDescriptor();

READYREQ.name = "ReadyReq"
READYREQ.full_name = ".ReadyReq"
READYREQ.nested_types = {}
READYREQ.enum_types = {}
READYREQ.fields = {}
READYREQ.is_extendable = false
READYREQ.extensions = {}
READYRES_PLAYERID_FIELD.name = "playerID"
READYRES_PLAYERID_FIELD.full_name = ".ReadyRes.playerID"
READYRES_PLAYERID_FIELD.number = 1
READYRES_PLAYERID_FIELD.index = 0
READYRES_PLAYERID_FIELD.label = 2
READYRES_PLAYERID_FIELD.has_default_value = false
READYRES_PLAYERID_FIELD.default_value = 0
READYRES_PLAYERID_FIELD.type = 5
READYRES_PLAYERID_FIELD.cpp_type = 1

READYRES_ALLID_FIELD.name = "allID"
READYRES_ALLID_FIELD.full_name = ".ReadyRes.allID"
READYRES_ALLID_FIELD.number = 2
READYRES_ALLID_FIELD.index = 1
READYRES_ALLID_FIELD.label = 3
READYRES_ALLID_FIELD.has_default_value = false
READYRES_ALLID_FIELD.default_value = {}
READYRES_ALLID_FIELD.type = 5
READYRES_ALLID_FIELD.cpp_type = 1

READYRES_MODELID_FIELD.name = "modelID"
READYRES_MODELID_FIELD.full_name = ".ReadyRes.modelID"
READYRES_MODELID_FIELD.number = 3
READYRES_MODELID_FIELD.index = 2
READYRES_MODELID_FIELD.label = 3
READYRES_MODELID_FIELD.has_default_value = false
READYRES_MODELID_FIELD.default_value = {}
READYRES_MODELID_FIELD.type = 5
READYRES_MODELID_FIELD.cpp_type = 1

READYRES.name = "ReadyRes"
READYRES.full_name = ".ReadyRes"
READYRES.nested_types = {}
READYRES.enum_types = {}
READYRES.fields = {READYRES_PLAYERID_FIELD, READYRES_ALLID_FIELD, READYRES_MODELID_FIELD}
READYRES.is_extendable = false
READYRES.extensions = {}
PLAYERACTION_PLAYERID_FIELD.name = "playerID"
PLAYERACTION_PLAYERID_FIELD.full_name = ".PlayerAction.playerID"
PLAYERACTION_PLAYERID_FIELD.number = 1
PLAYERACTION_PLAYERID_FIELD.index = 0
PLAYERACTION_PLAYERID_FIELD.label = 2
PLAYERACTION_PLAYERID_FIELD.has_default_value = false
PLAYERACTION_PLAYERID_FIELD.default_value = 0
PLAYERACTION_PLAYERID_FIELD.type = 5
PLAYERACTION_PLAYERID_FIELD.cpp_type = 1

PLAYERACTION_X_FIELD.name = "x"
PLAYERACTION_X_FIELD.full_name = ".PlayerAction.x"
PLAYERACTION_X_FIELD.number = 2
PLAYERACTION_X_FIELD.index = 1
PLAYERACTION_X_FIELD.label = 2
PLAYERACTION_X_FIELD.has_default_value = false
PLAYERACTION_X_FIELD.default_value = 0
PLAYERACTION_X_FIELD.type = 5
PLAYERACTION_X_FIELD.cpp_type = 1

PLAYERACTION_Y_FIELD.name = "y"
PLAYERACTION_Y_FIELD.full_name = ".PlayerAction.y"
PLAYERACTION_Y_FIELD.number = 3
PLAYERACTION_Y_FIELD.index = 2
PLAYERACTION_Y_FIELD.label = 2
PLAYERACTION_Y_FIELD.has_default_value = false
PLAYERACTION_Y_FIELD.default_value = 0
PLAYERACTION_Y_FIELD.type = 5
PLAYERACTION_Y_FIELD.cpp_type = 1

PLAYERACTION.name = "PlayerAction"
PLAYERACTION.full_name = ".PlayerAction"
PLAYERACTION.nested_types = {}
PLAYERACTION.enum_types = {}
PLAYERACTION.fields = {PLAYERACTION_PLAYERID_FIELD, PLAYERACTION_X_FIELD, PLAYERACTION_Y_FIELD}
PLAYERACTION.is_extendable = false
PLAYERACTION.extensions = {}

PlayerAction = protobuf.Message(PLAYERACTION)
ReadyReq = protobuf.Message(READYREQ)
ReadyRes = protobuf.Message(READYRES)

