-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('KCPService_pb')


local OPENKCPREQ = protobuf.Descriptor();
local OPENKCPRES = protobuf.Descriptor();
local OPENKCPRES_CONVID_FIELD = protobuf.FieldDescriptor();
local CLOSEKCPREQ = protobuf.Descriptor();
local CLOSEKCPRES = protobuf.Descriptor();
local CLOSEKCPRES_CONVID_FIELD = protobuf.FieldDescriptor();

OPENKCPREQ.name = "OpenKCPReq"
OPENKCPREQ.full_name = ".OpenKCPReq"
OPENKCPREQ.nested_types = {}
OPENKCPREQ.enum_types = {}
OPENKCPREQ.fields = {}
OPENKCPREQ.is_extendable = false
OPENKCPREQ.extensions = {}
OPENKCPRES_CONVID_FIELD.name = "convID"
OPENKCPRES_CONVID_FIELD.full_name = ".OpenKCPRes.convID"
OPENKCPRES_CONVID_FIELD.number = 1
OPENKCPRES_CONVID_FIELD.index = 0
OPENKCPRES_CONVID_FIELD.label = 2
OPENKCPRES_CONVID_FIELD.has_default_value = false
OPENKCPRES_CONVID_FIELD.default_value = 0
OPENKCPRES_CONVID_FIELD.type = 5
OPENKCPRES_CONVID_FIELD.cpp_type = 1

OPENKCPRES.name = "OpenKCPRes"
OPENKCPRES.full_name = ".OpenKCPRes"
OPENKCPRES.nested_types = {}
OPENKCPRES.enum_types = {}
OPENKCPRES.fields = {OPENKCPRES_CONVID_FIELD}
OPENKCPRES.is_extendable = false
OPENKCPRES.extensions = {}
CLOSEKCPREQ.name = "CloseKCPReq"
CLOSEKCPREQ.full_name = ".CloseKCPReq"
CLOSEKCPREQ.nested_types = {}
CLOSEKCPREQ.enum_types = {}
CLOSEKCPREQ.fields = {}
CLOSEKCPREQ.is_extendable = false
CLOSEKCPREQ.extensions = {}
CLOSEKCPRES_CONVID_FIELD.name = "convID"
CLOSEKCPRES_CONVID_FIELD.full_name = ".CloseKCPRes.convID"
CLOSEKCPRES_CONVID_FIELD.number = 1
CLOSEKCPRES_CONVID_FIELD.index = 0
CLOSEKCPRES_CONVID_FIELD.label = 2
CLOSEKCPRES_CONVID_FIELD.has_default_value = false
CLOSEKCPRES_CONVID_FIELD.default_value = 0
CLOSEKCPRES_CONVID_FIELD.type = 5
CLOSEKCPRES_CONVID_FIELD.cpp_type = 1

CLOSEKCPRES.name = "CloseKCPRes"
CLOSEKCPRES.full_name = ".CloseKCPRes"
CLOSEKCPRES.nested_types = {}
CLOSEKCPRES.enum_types = {}
CLOSEKCPRES.fields = {CLOSEKCPRES_CONVID_FIELD}
CLOSEKCPRES.is_extendable = false
CLOSEKCPRES.extensions = {}

CloseKCPReq = protobuf.Message(CLOSEKCPREQ)
CloseKCPRes = protobuf.Message(CLOSEKCPRES)
OpenKCPReq = protobuf.Message(OPENKCPREQ)
OpenKCPRes = protobuf.Message(OPENKCPRES)

