-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('UdpLostPackage_pb')


local UDPLOSTPACKAGE = protobuf.Descriptor();
local UDPLOSTPACKAGE_LISTSEQID_FIELD = protobuf.FieldDescriptor();

UDPLOSTPACKAGE_LISTSEQID_FIELD.name = "listSeqID"
UDPLOSTPACKAGE_LISTSEQID_FIELD.full_name = ".UdpLostPackage.listSeqID"
UDPLOSTPACKAGE_LISTSEQID_FIELD.number = 1
UDPLOSTPACKAGE_LISTSEQID_FIELD.index = 0
UDPLOSTPACKAGE_LISTSEQID_FIELD.label = 3
UDPLOSTPACKAGE_LISTSEQID_FIELD.has_default_value = false
UDPLOSTPACKAGE_LISTSEQID_FIELD.default_value = {}
UDPLOSTPACKAGE_LISTSEQID_FIELD.type = 5
UDPLOSTPACKAGE_LISTSEQID_FIELD.cpp_type = 1

UDPLOSTPACKAGE.name = "UdpLostPackage"
UDPLOSTPACKAGE.full_name = ".UdpLostPackage"
UDPLOSTPACKAGE.nested_types = {}
UDPLOSTPACKAGE.enum_types = {}
UDPLOSTPACKAGE.fields = {UDPLOSTPACKAGE_LISTSEQID_FIELD}
UDPLOSTPACKAGE.is_extendable = false
UDPLOSTPACKAGE.extensions = {}

UdpLostPackage = protobuf.Message(UDPLOSTPACKAGE)

