-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('UdpPackage_pb')


local UDPPACKAGE = protobuf.Descriptor();
local UDPPACKAGE_POSX_FIELD = protobuf.FieldDescriptor();
local UDPPACKAGE_POSY_FIELD = protobuf.FieldDescriptor();

UDPPACKAGE_POSX_FIELD.name = "posX"
UDPPACKAGE_POSX_FIELD.full_name = ".UdpPackage.posX"
UDPPACKAGE_POSX_FIELD.number = 2
UDPPACKAGE_POSX_FIELD.index = 0
UDPPACKAGE_POSX_FIELD.label = 2
UDPPACKAGE_POSX_FIELD.has_default_value = false
UDPPACKAGE_POSX_FIELD.default_value = 0
UDPPACKAGE_POSX_FIELD.type = 5
UDPPACKAGE_POSX_FIELD.cpp_type = 1

UDPPACKAGE_POSY_FIELD.name = "posY"
UDPPACKAGE_POSY_FIELD.full_name = ".UdpPackage.posY"
UDPPACKAGE_POSY_FIELD.number = 3
UDPPACKAGE_POSY_FIELD.index = 1
UDPPACKAGE_POSY_FIELD.label = 2
UDPPACKAGE_POSY_FIELD.has_default_value = false
UDPPACKAGE_POSY_FIELD.default_value = 0
UDPPACKAGE_POSY_FIELD.type = 5
UDPPACKAGE_POSY_FIELD.cpp_type = 1

UDPPACKAGE.name = "UdpPackage"
UDPPACKAGE.full_name = ".UdpPackage"
UDPPACKAGE.nested_types = {}
UDPPACKAGE.enum_types = {}
UDPPACKAGE.fields = {UDPPACKAGE_POSX_FIELD, UDPPACKAGE_POSY_FIELD}
UDPPACKAGE.is_extendable = false
UDPPACKAGE.extensions = {}

UdpPackage = protobuf.Message(UDPPACKAGE)

